# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: metagenomics
channels:
 - defaults
 - conda-forge
 - bioconda
dependencies:
 - conda-forge::openjdk=8.0.144 
 - fastqc=0.11.7
 - pathoscope=2.0.6
 - metaphlan2=2.7.7
 - kraken=0.10.5beta
 - trimmomatic=0.36
 - kaiju=1.6.2
 - multiqc=1.5
